### ISSUE TITLE
unable to  run in the windows 

### ISSUE THREAD

**Issue by Lpker-2006** [urbanadventurer/username-anarchy#1]
how can i make the tools work in the window

**Comment by EmreOvunc** [comment]
> how can i make the tools work in the window
@Lpker-2006

I explained step by step, how you can use it.

### Download Ruby for Windows
```
https://rubyinstaller.org/downloads/
```

### Install Ruby on Windows 
![](https://emreovunc.com/images/username_anarchy_02.png)

### Run the tool from terminal
```
ruby username-anarchy
```
![](https://emreovunc.com/images/username_anarchy_01.png)

**Comment by urbanadventurer** [comment]
Thanks @EmreOvunc for helping 👍

**Comment by Lpker-2006** [comment]
> > how can i make the tools work in the window
> > @Lpker-2006
> 
> I explained step by step, how you can use it.
> 
> ### Download Ruby for Windows
> ```
> https://rubyinstaller.org/downloads/
> ```
> 
> ### Install Ruby on Windows
> ![](https://camo.githubusercontent.com/99c21bf3bf33ac1da7d2fdcbb41bca22b1e9ad41/68747470733a2f2f656d72656f76756e632e636f6d2f696d616765732f757365726e616d655f616e61726368795f30322e706e67)
> 
> ### Run the tool from terminal
> ```
> ruby username-anarchy
> ```
> 
> ![](https://camo.githubusercontent.com/d5e340922d89ed8b0041d9d42728fe8e1e08f498/68747470733a2f2f656d72656f76756e632e636f6d2f696d616765732f757365726e616d655f616e61726368795f30312e706e67)

thank you for  helping
